services:
  dev:
    build: .
    container_name: aechat-links-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - YARN_IGNORE_PATH=1
      - YARN_NODE_LINKER=node-modules
    command: yarn dev --host
    networks:
      - dev_network

volumes:
  node_modules:
    name: aechat-links-node_modules

networks:
  dev_network:
    name: aechat-links-dev-server
